//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EmployeetImages = new HashSet<EmployeetImage>();
            this.Products = new HashSet<Product>();
            this.Users = new HashSet<User>();
        }
    
        public int id { get; set; }
        [Display(Name ="Name")]
        [Required]
        public string name { get; set; }
        [Display(Name = "Address")]
        [Required]
        public string address { get; set; }
        [Display(Name = "Email")]
        [Required]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }
        [Display(Name = "Phone")]
        [Required]
        [DataType(DataType.PhoneNumber)]
        public string phone { get; set; }
        [Display(Name = "Salary")]
        [Required]
        public Nullable<decimal> slary { get; set; }
        public string addedBy { get; set; }
        [Display(Name = "NID NO")]
        [Required]
        public string nationalIdNumber { get; set; }
        [Display(Name = "Date of Birth")]
        [Required]
        [DataType(DataType.Date)]
        public string dateOfBirth { get; set; }
        [Display(Name = "Gender")]
        [Required]
        public Nullable<int> genderId { get; set; }
        [Display(Name = "Departmen")]
        [Required]
        public Nullable<int> departmentId { get; set; }
        [Display(Name = "Designation")]
        [Required]
        public Nullable<int> designationId { get; set; }
        [Display(Name = "Religion")]
        [Required]
        public Nullable<int> religionId { get; set; }
        [Display(Name = "City")]
        [Required]
        public Nullable<int> cityId { get; set; }
        [Display(Name = "Join Date")]
        [Required]
        [DataType(DataType.Date)]
        public string joinDate { get; set; }
        [Display(Name = "Add Date")]
        [Required]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> employeeAddedDate { get; set; }
        
        public Nullable<bool> status { get; set; }
    
        public virtual City City { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Religion Religion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeetImage> EmployeetImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
