//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class EmployeetImage
    {
        public int id { get; set; }
        [Display(Name ="Employee")]
        public Nullable<int> empId { get; set; }
        [Required]
        [Display(Name ="Image")]
        public string image { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
