//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int id { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<System.DateTime> purchaseDate { get; set; }
        public Nullable<int> unitId { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> supplierId { get; set; }
        public string addedBy { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
