//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.Purchases = new HashSet<Purchase>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string addedBy { get; set; }
        public string nationalIdNumber { get; set; }
        public string dateOfBirth { get; set; }
        public Nullable<int> genderId { get; set; }
        public Nullable<int> departmentId { get; set; }
        public Nullable<int> designationId { get; set; }
        public Nullable<int> religionId { get; set; }
        public Nullable<int> cityId { get; set; }
        public Nullable<int> orgainzationId { get; set; }
        public Nullable<System.DateTime> SupplierAddedDate { get; set; }
        public Nullable<bool> status { get; set; }
    
        public virtual City City { get; set; }
        public virtual Department Department { get; set; }
        public virtual Designation Designation { get; set; }
        public virtual Gender Gender { get; set; }
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase> Purchases { get; set; }
        public virtual Religion Religion { get; set; }
    }
}
