//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        public int id { get; set; }
        [Required]
        [Display(Name = "Name")]
        public string name { get; set; }
        [Display(Name ="Password")]
        [Required]
        [DataType(DataType.Password)]
        public string password { get; set; }
        [Display(Name = "User Role")]
        public Nullable<int> roleId { get; set; }
        public Nullable<int> empid { get; set; }
        public string addedBy { get; set; }
        public Nullable<System.DateTime> userAddedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
